spring:
  profiles: eureka01
  application:
    name: eureka01

server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://212.64.16.147:3002/eureka
  instance:
    hostname: lcoalhost

---

server:
  port: 3002

spring:
  profiles: eureka02
  application:
    name: eureka02

eureka:
  client:
    service-url:
      defaultZone: http://212.64.16.147:3001/eureka
  instance:
    hostname: lcoalhost
